CREATE OR REPLACE PACKAGE EX2RGG.RESPUESTAS_EXAMEN02
AS
    PROCEDURE RESPUESTA_01(MUSICO_BANDA OUT SYS_REFCURSOR);
    PROCEDURE RESPUESTA_02(NEW_CONCERT OUT SYS_REFCURSOR);
    PROCEDURE RESPUESTA_03(MI OUT SYS_REFCURSOR);
    PROCEDURE RESPUESTA_04(GIRA OUT SYS_REFCURSOR);
END RESPUESTAS_EXAMEN02;