-- 1-Registrar a un músico (Banjo, Accordion), asignarlo a la banda con el menor numero de integrantes;

SELECT BANDA.BAND_ID , COUNT(*) MEMBERS FROM MUDB.BANDS_MUSICIANS BANDA
GROUP BY BANDA.BAND_ID HAVING COUNT(*) >= 1
ORDER BY MEMBERS ASC
--870 BAND

CREATE OR REPLACE PROCEDURE EX2CAM.CREARMUSICO (M_NAME IN VARCHAR2, M_BIRTH IN DATE, M_DIED IN DATE, M_ORIGINID IN NUMBER, M_RESIDENCEID IN NUMBER, RESPONSE OUT VARCHAR2)
IS 
   TMPVAR VARCHAR2 (100);
BEGIN
    TMPVAR := 'OK';
    INSERT INTO MUDB.MUSICIANS MUS
    VALUES (MUSICIANS_SEQ.NEXTEMVARAL, M_NAME, M_BIRTH, M_DIED, M_ORIGINID, M_RESIDENCEID); 
END CREARMUSICO;
DECLARE 
    TEMVAR VARCHAR2 (100);
BEGIN
    EX2CAM.CREARMUSICO('Jose Guadalupe Esparza ','07-DEC-1945', '29-MAR-1987' , 72, 35, TEMVAR);
    DBMS_OUTPUT.PUT_LINE(TEMVAR);
END;




CREATE OR REPLACE PROCEDURE EX2CAM.ADDINSTRUMENT(BMID IN NUMBER, I_ID IN NUMBER, G_ID IN NUMBER, RESPONSE OUT VARCHAR2)
IS 
    TMVVAR VARCHAR2(100);
BEGIN
    TMVVAR := 'OK';
    INSERT INTO MUDB.BANDS_MUSICIANS_INSTRUMENTS BMI
    VALUES (BMID, I_ID, G_ID );
END ADDINSTRUMENT;
DECLARE
    TEMVAR VARCHAR2 (100);
BEGIN
    EX2CAM.ADDINSTRUMENT(3001, 1, 3,TEMVAR);
    EX2CAM.ADDINSTRUMENT(3001, 35, 3,TEMVAR);
    DBMS_OUTPUT.PUT_LINE(TEMVAR);
END;
-- ACORDEON 1 BANJO 35




CREATE OR REPLACE PROCEDURE EX2CAM.MUSICOABANDA(B_ID IN NUMBER, M_ID IN NUMBER)
IS
    TMVVAR VARCHAR2(100);
BEGIN
    TMVVAR := 'OK';
    INSERT INTO MUDB.BANDS_MUSICIANS BM
    VALUES (BAND_MUSICIAN_SEQ.NEXTEMVARAL, B_ID, M_ID);
END MUSICOABANDA;
DECLARE
    TEMVAR VARCHAR2 (100);
BEGIN 
    EX2CAM.MUSICOABANDA(73, 1501, TEMVAR);
    DBMS_OUTPUT.PUT_LINE(TEMVAR);
END;