/*2-Crear un concierto CONCIERTO BANDAdas del género que más CONCIERTOciertos tenga registrados desde 1950;
Ordenar a las BANDAdas de acuerdo a su promedio de público en sus CONCIERTOciertos (Asumiendo que todos son sold out).
Mostrar las BANDAdas participantes y su orden.*/


SELECT EXTRACT (YEAR FROM CONCIERTO.CONCIERTOCERT_DATE) ANOS,
       GENEROS.MUSIC_GENRE_ID,
       GENEROS.GENRE_NAME
  FROM EX2CAM.CONCIERTOCERTS  CONCIERTO
       INNER JOIN EX2CAM.CONCIERTOCERTS_BANDADS NCONCIERTOCIERTOS
           ON NCONCIERTOCIERTOS.CONCIERTOCERT_ID = CONCIERTO.CONCIERTOCERT_ID
       INNER JOIN EX2CAM.BANDADS BANDA
           ON BANDA.BANDAD_ID = NCONCIERTOCIERTOS.BANDAD_ID
       INNER JOIN EX2CAM.MUSIC_GENRES GENEROS
           ON GENEROS.MUSIC_GENRE_ID = BANDA.MUSIC_GENRE_ID
 WHERE EXTRACT (YEAR FROM CONCIERTO.CONCIERTOCERT_DATE) >= 1950;

  SELECT GENEROS.MUSIC_GENRE_ID, COUNT (*) CANTIDAD
    FROM EX2CAM.CONCIERTOCERTS CONCIERTO
         INNER JOIN EX2CAM.CONCIERTOCERTS_BANDADS NCONCIERTOCIERTOS
             ON NCONCIERTOCIERTOS.CONCIERTOCERT_ID = CONCIERTO.CONCIERTOCERT_ID
         INNER JOIN EX2CAM.BANDADS BANDA
             ON BANDA.BANDAD_ID = NCONCIERTOCIERTOS.BANDAD_ID
         INNER JOIN EX2CAM.MUSIC_GENRES GENEROS
             ON GENEROS.MUSIC_GENRE_ID = BANDA.MUSIC_GENRE_ID
GROUP BY GENEROS.MUSIC_GENRE_ID
ORDER BY CANTIDAD DESC;