CREATE OR REPLACE PROCEDURE IBARRA2.MUSIC_GENRE_PRO_MOST(IDGENR OUT INTEGER)
IS
BEGIN
SELECT MUSIC_GENRE_ID INTO IDGENR FROM(
SELECT MUSIC_GENRE_ID 
FROM(
    SELECT CONCERT_DATE, BAND_NAME, AXXX.MUSIC_GENRE_ID, AX.CONCERT_ID
    FROM MUDB.CONCERTS AX
    INNER JOIN MUDB.CONCERTS_BANDS AXX ON AX.CONCERT_ID = AXX.CONCERT_ID
    INNER JOIN MUDB.BANDS AXXX ON AXX.BAND_ID = AXXX.BAND_ID
    INNER JOIN MUDB.MUSIC_GENRES AXXXX ON AXXX.MUSIC_GENRE_ID = AXXXX.MUSIC_GENRE_ID)
    WHERE CONCERT_DATE >= '01-ENE-1950'
    GROUP BY MUSIC_GENRE_ID
    ORDER BY COUNT(CONCERT_ID) DESC
    )
    WHERE ROWNUM =1;
    
END MUSIC_GENRE_PRO_MOST;

/
CREATE OR REPLACE PROCEDURE IBARRA2.CONCERTS_PRO_ADD(
a_Venu  IN  MUDB.CONCERTS.CONCERT_VENUE_ID%TYPE,
a_Date  IN  MUDB.CONCERTS.CONCERT_DATE%TYPE,
a_Orga  IN  MUDB.CONCERTS.CONCERT_ORGANIZER_ID%TYPE,
a_Tempo OUT INTEGER
)
IS
    BEGIN
    INSERT INTO MUDB.CONCERTS("CONCERT_ID","CONCERT_VENUE_ID","CONCERT_DATE","CONCERT_ORGANIZER_ID")
    VALUES (MUDB.CONCERTS_SEQ.NEXTVAL, a_Venu, a_Date, a_Orga);
    a_Tempo := MUDB.CONCERTS_SEQ.CURRVAL;
    END CONCERTS_PRO_ADD;
/
CREATE OR REPLACE PROCEDURE IBARRA2.CONCERTS_BANDS_PRO_ADD(
a_Idco IN MUDB.CONCERTS_BANDS.CONCERT_ID%TYPE,
a_Idba IN MUDB.CONCERTS_BANDS.BAND_ID%TYPE,
a_Song IN MUDB.CONCERTS_BANDS.PLAYED_SONGS%TYPE,
a_Orde IN MUDB.CONCERTS_BANDS.BAND_ORDER%TYPE)
IS
BEGIN
INSERT INTO MUDB.CONCERTS_BANDS("CONCERT_ID","BAND_ID","PLAYED_SONGS","BAND_ORDER")
VALUES(a_Idco,a_Idba,a_Song,a_Orde);
END CONCERTS_BANDS_PRO_ADD;
/
CREATE OR REPLACE PROCEDURE IBARRA2.RESPONSE_02_CUR(
IDGENR IN INTEGER,
IDCONC IN MUDB.CONCERTS_BANDS.CONCERT_ID%TYPE,
a_Song IN MUDB.CONCERTS_BANDS.PLAYED_SONGS%TYPE
)
AS
        CURSOR BANDS_A IS
        SELECT BAN.BAND_NAME, BAN.BAND_ID, MUDB.BANDS_FUN_AVG(SUM(CAPACITY),COUNT(CAPACITY)) AS AVR
            FROM MUDB.CONCERTS	CON
            INNER JOIN MUDB.CONCERT_VENUES VEN ON CON.CONCERT_VENUE_ID = VEN.CONCERT_VENUE_ID
            INNER JOIN MUDB.CONCERTS_BANDS COB ON CON.CONCERT_ID = COB.CONCERT_ID
            INNER JOIN MUDB.BANDS    BAN ON COB.BAND_ID = BAN.BAND_ID
            WHERE IDGENR = BAN.MUSIC_GENRE_ID
            GROUP BY BAN.BAND_NAME, BAN.BAND_ID
            ORDER BY MUDB.BANDS_FUN_AVG(SUM(CAPACITY),COUNT(CAPACITY)) ASC;
        BANDS_B BANDS_A%ROWTYPE;
        TYPE BANDS_T IS TABLE OF BANDS_B%TYPE;
        L_BANDS BANDS_T;
        
        BEGIN
            OPEN BANDS_A;
            FETCH BANDS_A BULK COLLECT INTO L_BANDS;
            CLOSE BANDS_A;
            
            FOR INDX IN 1..L_BANDS.COUNT LOOP
                DBMS_OUTPUT.PUT_LINE(L_BANDS(INDX).BAND_NAME);
                MUDB.CONCERTS_BANDS_PRO_ADD(IDCONC,L_BANDS(INDX).BAND_ID, a_Song, INDX);
                END LOOP;
    END RESPONSE_02_CUR;
    /