/* Formatted on 4/27/2017 4:03:46 PM (QP5 v5.300) */
SELECT *
  FROM session_privs
 WHERE privilege LIKE 'GRANT RESOURCE%';

GRANT CREATE TABLE TO examen02;
GRANT CREATE SEQUENCE TO examen02;
GRANT CREATE PROCEDURE TO examen02;
GRANT CREATE TRIGGER TO examen02;
GRANT CREATE USER TO examen02;
GRANT ALTER USER TO examen02;
GRANT DROP USER TO examen02;
GRANT CREATE TABLESPACE TO examen02;
GRANT DROP TABLESPACE TO examen02;
GRANT CREATE SESSION TO examen02 WITH ADMIN OPTION;
GRANT CREATE TABLE TO examen02 WITH ADMIN OPTION;
GRANT CREATE SEQUENCE TO examen02 WITH ADMIN OPTION;
GRANT CREATE PROCEDURE TO examen02 WITH ADMIN OPTION;
GRANT CREATE TRIGGER TO examen02 WITH ADMIN OPTION;
GRANT RESOURCE TO examen02;