/* PAQUETE MAYOR DE TODO*/

CREATE OR REPLACE PACKAGE EX2MAR.MEGAEXAMEN
AS
    PROCEDURE N1;

    PROCEDURE N2;

    PROCEDURE N3;

    PROCEDURE N4;
END MEGAEXAMEN;
/

CREATE OR REPLACE PACKAGE BODY EX2MAR.MEGAEXAMEN
IS
    PROCEDURE N1
    IS
        TEMP1   SYS_REFCURSOR;
    BEGIN
        MUDB.NUM1.MAKE (TEMP1);
    END N1;

    PROCEDURE N2
    IS
        TEMP1   SYS_REFCURSOR;
    BEGIN
        MUDB.NUM2.MAKE (TEMP1);
    END N2;

    PROCEDURE N3
    IS
        TEMP1   SYS_REFCURSOR;
    BEGIN
        MUDB.NUM3.MAKE (TEMP1);
    END N3;

    PROCEDURE N4
    IS
        TEMP1   SYS_REFCURSOR;
    BEGIN
        MUDB.NUM4.MAKE;
    END N4;
END MEGAEXAMEN;